[package]
name = "renderer"
version = "0.1.0"
authors = ["owen"]

[dependencies]
nalgebra = "0.12.3"
image = "0.14.0"
rand = "0.3"
scoped_threadpool = "0.1.7"

[profile.release]
debug = true

[features]
default = []

profile = []
